### ISSUE TITLE
Things to improve, note from Steemer

### ISSUE THREAD

**Issue by noisy** [adcpm/steem#1]
* remove `.idea` from git
* commit message is not a plaheholder for word "commit" - please describe what specific commits ads new

**Comment by adcpm** [comment]
Thank for contribute i will working on it. I not sure why my .gitignore dont ignore .idea .save yet. Any through?  https://github.com/adcpm/steem/blob/master/.gitignore

**Comment by adcpm** [comment]
I find out!
