### ISSUE TITLE
Create Posts

### ISSUE THREAD

**Issue by keverw** [adcpm/steem#11]
Is it possible to use this to create a blog post?

It seems like it's mainly just for logging in and reading data at this point - which is a great start.

**Comment by adcpm** [comment]
Sure. You need to create a tx, sign it and boradcast it with broadcastTransaction method.

**Comment by DrmedWurst** [comment]
Can you please provide an example?
it is not that obvious

**Comment by adcpm** [comment]
You can use now the method steem.broadcast.comment() to post an article or comment. Here is an example: 
```
var steem = require('steem');

var wif = steem.auth.toWif(username, password, 'posting');
steem.broadcast.comment(wif, '', 'steemjs', username, 'this-is-a-test', 'Test Title', 'Hello World!', {tags: ['steemjs', 'steem']}, function(err, result) {
	console.log(err, result);
});
```

**Comment by DrmedWurst** [comment]
Thank you very much! I will try it ;-) Will there be also a REST API in future?

**Comment by adcpm** [comment]
No sorry no Rest API in the future. The Rest API is in the present ;) here : https://api.steemjs.com/getAccounts?names[]=fabien
It's working like the package. This API not include the broadcast methods. I'm now developing Steem Connect it will handle the broadcast.

**Comment by gaupoit** [comment]
Thanks @bonustrack for nice tip.

**Comment by vuvuongvi** [comment]
Thanks you so much,so helpful with me
