### ISSUE TITLE
Actionscript compile fail

### ISSUE THREAD

**Issue by graphenepay** [adcpm/steem#15]
When using npm install steem, it's impossible to compile for mobile usage.

```
:processF0DebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processF0DebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\steve\AppData\Local\Android\android-sdk\build-tools\23.0.3\aapt.exe'' finished with non-zero exit value 1
```

Most likely a dependency or path issue

**Comment by adcpm** [comment]
Is this a react native app?

**Comment by steempayments** [comment]
No. It's native, but not a react app.
I've boiled it down to having an error on steemauth.

You can always join me on https://steemit.chat/direct/steve-walschot for direct chat

**Comment by steempayments** [comment]
Fyi: "steem": "adcpm/steem#b6c3f6eaaa57e5ae1c18a937a10c99ed74d8b700" is working.

**Comment by nil1511** [comment]
@steempayments can you check using latest version?

**Comment by yamadapc** [comment]
`b6c3f6eaaa57e5ae1c18a937a10c99ed74d8b700` didn't have the `steemauth` dependency. I'd guess it didn't use Node.js' crypto or other modules you have to shim.
