### ISSUE TITLE
accountUpdate fails in compiled build.

### ISSUE THREAD

**Issue by nil1511** [adcpm/steem#31]
In frontend it fails from dev.steemconnect.com but working fine from localhost. Mostly problem in webpack bundling or something.also promise warning does not occurs locally.

```Warning: a promise was created in a handler but was not returned from it, see http://goo.gl/rRqMUw
Error: WebSocket is already in CLOSING or CLOSED state.```

**Comment by yamadapc** [comment]
What's the version?

**Comment by nil1511** [comment]
0.3.25

**Comment by yamadapc** [comment]
Do I reproduce if I visit the website now?

**Comment by nil1511** [comment]
Yes.It is still reproducible on latest version 0.3.26.
