### ISSUE TITLE
GOLOS

### ISSUE THREAD

**Issue by dacom-dark-sun** [adcpm/steem#42]
I trying to change parameter in library for contact it with Golos:
`
 var A = {
            url: "127.0.0.1:8090", ..... 
`
But of course i have answer: 
`SyntaxError: Failed to construct 'WebSocket': The URL '127.0.0.1:8090' is invalid`
How i can configure it for work with Golos blockchain?

**Comment by adcpm** [comment]
Can you try with http:// prefix?

**Comment by dacom-dark-sun** [comment]
No, this is still now work, cause library still trying connection to wss://steemit.com/wspa. 
And second problem. When i try convert private key to pub key, i have preffix like: "STM", but we use "GLS". So, this i change, but broadcast still going throw Steemit.

So, better i ask team about official node, which works throw websocket? Or you have one more solution?

**Comment by adcpm** [comment]
Yes you could try with this WS wss://ws.golos.io see if it solve the issue.

**Comment by dacom-dark-sun** [comment]
I have changed node to url: "wss://ws.golos.io" and connection establishment successful. I change prefix STM to GLS everywhere. But when i broadcast vote, i see:
Error: 3030008 tx_missing_posting_auth: missing required posting authority

And reason - wrong conversion wif to pub key.

`Error: 3030008 tx_missing_posting_auth: missing required posting authority`
`Missing Posting Authority dark.sun`
`{"id":"dark.sun","posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS77wx6Remi2hiG8zVaDAfJJGcWWkXCQjooYeqUXNqMcy3ceEWL5",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS6DpEiFL9wUCcU5i1px32bg3JRfuj6b2cAQJDe6LXEAEau3h4Hu",1]]},"owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS5SuW1agnFV86Fb3zKMrax4sRXUq6gdUhZt8Wqwv7PdeVEhE4dh",1]]}}
    th_a  transaction.cpp:132 verify_authority`

`{"ops":[["vote",{"voter":"dark.sun","author":"lesnik","permlink":"sobranie-khudozhestvennyi-rasskaz","weight":10000}]],"sigs":["GLS7X2yxbRbna7ExBS9kSq7frmYCyVPtNp1Lf2hf51xaWT44t6yD3"]}
    th_a  transaction.cpp:174 verify_authority`

`{"*this":{"ref_block_num":49728,"ref_block_prefix":1673285747,"expiration":"2016-12-13T21:20:32","operations":[["vote",{"voter":"dark.sun","author":"lesnik","permlink":"sobranie-khudozhestvennyi-rasskaz"...8432226f44424bcbb5f02f586dafd"]}}
    th_a  transaction.cpp:287 verify_authority`

`{"trx":{"ref_block_num":49728,"ref_block_prefix":1673285747,"expiration":"2016-12-13T21:20:32","operations":[["vote",{"voter":"dark.sun","author":"lesnik","permlink":"sobranie-khudozhestvennyi-rasskaz","weight":10000}]],"extensions":[],"signatures":["…`

Any suggestions? When i command 
`getKeyReference` - all works good.

**Comment by dacom-dark-sun** [comment]
So, what can i do? 
Always, when i sign vote transaction, i have different key in error message:

 {"ops":[["vote",{"voter":"dark.sun","author":"natka2","permlink":"zharkii-ogon","weight":10000}]],"sigs":["GLS7bSTdfLrNVLYe7GE1JLrXXqBPnk4edvg3RLwiGcHzhQuJ5bHBU"]}
    th_a  transaction.cpp:174 verify_authority

  {"ops":[["vote",{"voter":"dark.sun","author":"natka2","permlink":"zharkii-ogon","weight":10000}]],"sigs":["GLS6euRymsEN1X96d4r7c2eLd76tLw3ENTWyucBTymhFUcKFtVyGS"]}
    th_a  transaction.cpp:174 verify_authority

How i can fix it?

**Comment by dacom-dark-sun** [comment]
We have chain ID = 00000000000000000000000000000000, what effect it can have?

**Comment by dacom-dark-sun** [comment]
After change chain-if all works fine. Thanks for attention. %)
