### ISSUE TITLE
Can you give examples for the query param

### ISSUE THREAD

**Issue by bjrenfrow** [adcpm/steem#5]
Specifically on the`Get Discussions By` API?

**Comment by adcpm** [comment]
You can do like this: 

```javascript
const 
steem.api.getDiscussionsByTrending({
  tag: 'introduceyourself',
  limit: 10,
  start_author: 'lada94',
  start_permlink: 'introduce-youself-steemit'
}, (err, result) => {
  console.log(err, result);
});
```

**Comment by msg768** [comment]
I tried your query on getDiscussionsByCreated and it seems like it ignores pretty much all the parameters except limit. :/

**Comment by nkgokul** [comment]
It would be great to have the details of the query parameter. I don't see the details anywhere on net.

**Comment by Katamori** [comment]
Seconded!

For instance, I'm interested if all the four parameters mentioned by @bonustrack are possible.
