### ISSUE TITLE
Login Function Not Working?

### ISSUE THREAD

**Issue by fletchertyler914** [adcpm/steem#7]
When I use the steem.login function, no matter what account name or password I use it always returns "True". I was assuming this was an actual login function to log in to the steem account?

**Comment by KaptainKrayola** [comment]
Steemd only replies with True or False.  It's not a limitation of steemjs, just how the steemd application works.

**Comment by fletchertyler914** [comment]
Right, but I ONLY get a true return, even with invalid creds. For Example: 
`    steem.login('tyler-fletcher', '12345', function(err, result) {
        console.log(err, result);
    });`
will return true, even though 12345 is not my password.

**Comment by KaptainKrayola** [comment]
oh, interesting.  I wonder if the client itself is not working correctly then.  Have you tried with both the piston.rocks url and the steemit.com WS api?

**Comment by fletchertyler914** [comment]
I am using the piston.rocks api, I will stry steemits!

**Comment by KaptainKrayola** [comment]
steemit.com/wspa in case you need the URL

**Comment by fletchertyler914** [comment]
Seems to be doing the same thing with steemit's API. I can literally get a true value from passing no parameters for the username and password:
 `steem.login('', '', function(err, result) {
        console.log(err, result);
    });`

**Comment by KaptainKrayola** [comment]
Must be an issue with steemd itself then.  Possible that the method is not implemented yet and just always returns true.  If you were inclined you could check the source code and see what it's doing.  I don't believe this to be an issue with steemjs though

**Comment by fletchertyler914** [comment]
I am looking through the source code now. Doesn't seem to be an issue with SteemJS Now. we can call this closed, Thanks!

**Comment by KaptainKrayola** [comment]
You're welcome.  Do me a favor and update the ticket with your findings please.
