### ISSUE TITLE
GetFollowing documentation

### ISSUE THREAD

**Issue by wmbutler** [adcpm/steem#8]
```
steem.getFollowing(follower, startFollowing, followType, limit, function(err, result) {
    console.log(err, result);
});
```

Any chance you can post an example for the parameters in this function?

- follower 'billbutler'
- startFollowing ?
- followType ?

**Comment by adcpm** [comment]
There was an issue due to the recent update of the get_following method, I was missing the new attribute and the package was not working for this method. I've now updated the package to 0.2.20 and it work. Here is fews examples : https://github.com/adcpm/steem/blob/master/test.js

**Comment by adcpm** [comment]
`steem.getFollowing('ned', 0, 'blog', 10, function(err, result) {
	console.log(err, result);
});
`
