### ISSUE TITLE
Login returns true

### ISSUE THREAD

**Issue by wmbutler** [adcpm/steem#9]
Hey, looks like I guessed @ned's password :)

```
steem.login('ned', '****************', function(err, result) {
    console.log(err, result);
});
```
Returns true! Woohoo!

**Comment by adcpm** [comment]
Fuck! I forgot to hide it on the commit. Please dont power down 100K$.

**Comment by adcpm** [comment]
The real answer is that the blockchain actually return true even if the password or username is wrong. If you need to verify a password you can use my other package steemconnect here: https://github.com/adcpm/steemconnect/blob/master/lib/auth.js#L10

**Comment by wmbutler** [comment]
Cool, thx.
